TorService JNI depends on LocalBroadcastManager
Fixes:

E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/localbroadcastmanager/content/LocalBroadcastManager;
E AndroidRuntime:        at org.torproject.jni.TorService.broadcastStatus(TorService.java:509)
E AndroidRuntime:        at org.torproject.jni.TorService.onCreate(TorService.java:235)

This reverts commit ad2394c6cb9ee2529eaa116731f6000ce15c4b84.