ACTION_STOP is now public in TorService
It is no longer necessary to define ACTION_STOP in OrbotConstants
because ACTION_STOP is now made public in TorService

Fixes build error:

app/src/main/java/org/torproject/android/service/OrbotService.java:635: error: reference
to ACTION_STOP is ambiguous
both variable ACTION_STOP in TorService and variable ACTION_STOP in OrbotConstants match